import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>I-Vent Tiket Konser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello</h1>
        <h1 style={{ color: "grey", padding: "90px" }}>
          Hello Selamat datang{" "}
        </h1>
      </main>
    </>
  );
}
